eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.56.102:8761/eureka/
      
server:
  port: 8764
  
spring:
  application:
    name: eshop-inventory-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.56.84:3306/eshop
    username: eshop
    password: eshop